// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSKWXDEILoKbP5LBVVXDgEjz7eDIBvP4g',
    appId: '1:499246098649:web:88edb739ea9e557df376c8',
    messagingSenderId: '499246098649',
    projectId: 'flutter-poksi',
    authDomain: 'flutter-poksi.firebaseapp.com',
    storageBucket: 'flutter-poksi.firebasestorage.app',
    measurementId: 'G-9TX0264WRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu7pU95veIIPbO8RyrRaYD31vg5KE7id8',
    appId: '1:499246098649:android:262d5f438e8ccf21f376c8',
    messagingSenderId: '499246098649',
    projectId: 'flutter-poksi',
    storageBucket: 'flutter-poksi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCts6Z8qbkmTSkxgxm-8DH0t-ro3OqCPcw',
    appId: '1:499246098649:ios:8db114f4a0536fcbf376c8',
    messagingSenderId: '499246098649',
    projectId: 'flutter-poksi',
    storageBucket: 'flutter-poksi.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCts6Z8qbkmTSkxgxm-8DH0t-ro3OqCPcw',
    appId: '1:499246098649:ios:8db114f4a0536fcbf376c8',
    messagingSenderId: '499246098649',
    projectId: 'flutter-poksi',
    storageBucket: 'flutter-poksi.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSKWXDEILoKbP5LBVVXDgEjz7eDIBvP4g',
    appId: '1:499246098649:web:c1c3313e6c20bd2df376c8',
    messagingSenderId: '499246098649',
    projectId: 'flutter-poksi',
    authDomain: 'flutter-poksi.firebaseapp.com',
    storageBucket: 'flutter-poksi.firebasestorage.app',
    measurementId: 'G-4XV1GN6XF7',
  );
}
